Rails.application.routes.draw do


  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  post "alerts/create"

  #get "alerts/get"

  post "alerts/delete"

  get "user/signup"  # this is generated by rails
  get "user/edit"
  post "user/update"

  post "user/signup" => "user#create"
  post "user/signin" # this is equivalent to the following?
  		     # post 'users/signup' => 'User#signup'
  get "/user/signin"
  get "user/signout" 
  
  post "/products/import"

  #resources :merchants


  #resources :catalogs


  #get "homepage/index"

  #resources :products


  get 'catalogs/:catalog_id' => 'show#show'
  get 'merchants/:merchant_id' => 'show#show'
  get 'show/search' => 'show#show'
  get 'catalogs' => 'show#list_catalogs'
  #get 'catalogs' => 'Catalogs#index' reverve catalogs controller for admin tasks
  get 'merchants' => 'show#list_merchants'
  #get 'merchants' => 'Merchants#index'
  post 'coupons/submit_deal(.:format)' => 'coupons#submit_deal'
  post 'coupons/delete_deal(.:format)' => 'coupons#delete_deal'
  get 'coupons/submit_deal(.:format)' => 'coupons#submit_deal'
  root to: 'show#show'


  # The priority is based upon order of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end
